alias rf='rm -rf'
alias ll='ls -la'
alias gs='git status'
alias ga='git add'
alias go='git checkout'
PS1='\[\033[0;34m\]\u @ \[\033[00m\] \[\033[0;32m\]\w >\[\033[00m\] '
alias gl='git log --graph --pretty=oneline --abbrev-commit'
